
# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2025.1.110.2.15
# Date: 2025-09-07 19:06

# Copyright (C) 2013 - 2025 Efinix Inc. All rights reserved.

# Device: T20F169
# Project: BRAM
# Timing Model: C3 (final)

# PLL Constraints
#################
create_clock -period 7.812 -name pll_clk [get_ports {pll_clk}]

# GPIO Constraints
####################
create_clock -period <USER_PERIOD> -name clk [get_ports {clk}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {rmii_crs_dv}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {rmii_crs_dv}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {rmii_rxd[0]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {rmii_rxd[0]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {CAM0_EN}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {CAM0_EN}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {CAM1_EN}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {CAM1_EN}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdc}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdc}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {rmii_tx_en}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {rmii_tx_en}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {rmii_txd[0]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {rmii_txd[0]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {rmii_txd[1]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {rmii_txd[1]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_i}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_i}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_o}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_o}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_oe}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_oe}]

# LVDS RX GPIO Constraints
############################
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {IO12_manual_reset_n}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {IO12_manual_reset_n}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {phy_intr_n}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {phy_intr_n}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {rmii_rx_er}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {rmii_rx_er}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {rmii_rxd[1]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {rmii_rxd[1]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led2}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led2}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {phy_rst_n}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {phy_rst_n}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {RJ45_led}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {RJ45_led}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led4}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led4}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led4_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led4_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led4_OE}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led4_OE}]

# LVDS Rx Constraints
####################

# LVDS TX GPIO Constraints
############################
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {FPGA_IO0_A0}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {FPGA_IO0_A0}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {FPGA_IO0_A1}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {FPGA_IO0_A1}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {FPGA_IO0_A2}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {FPGA_IO0_A2}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {I2C_SCL_IN}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {I2C_SCL_IN}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {I2C_SCL_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {I2C_SCL_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {I2C_SCL_OE}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {I2C_SCL_OE}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {I2C_SDA_IN}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {I2C_SDA_IN}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {I2C_SDA_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {I2C_SDA_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {I2C_SDA_OE}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {I2C_SDA_OE}]

# LVDS Tx Constraints
####################

# MIPI RX Constraints
#####################################
set_output_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -max 0.733 [get_ports {mipi_rx_inst1_VC_ENA[3] mipi_rx_inst1_VC_ENA[2] mipi_rx_inst1_VC_ENA[1] mipi_rx_inst1_VC_ENA[0]}]
set_output_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -min -0.069 [get_ports {mipi_rx_inst1_VC_ENA[3] mipi_rx_inst1_VC_ENA[2] mipi_rx_inst1_VC_ENA[1] mipi_rx_inst1_VC_ENA[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -max 1.409 [get_ports {mipi_rx_inst1_VSYNC[3] mipi_rx_inst1_VSYNC[2] mipi_rx_inst1_VSYNC[1] mipi_rx_inst1_VSYNC[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -min 0.542 [get_ports {mipi_rx_inst1_VSYNC[3] mipi_rx_inst1_VSYNC[2] mipi_rx_inst1_VSYNC[1] mipi_rx_inst1_VSYNC[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -max 1.401 [get_ports {mipi_rx_inst1_HSYNC[3] mipi_rx_inst1_HSYNC[2] mipi_rx_inst1_HSYNC[1] mipi_rx_inst1_HSYNC[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -min 0.539 [get_ports {mipi_rx_inst1_HSYNC[3] mipi_rx_inst1_HSYNC[2] mipi_rx_inst1_HSYNC[1] mipi_rx_inst1_HSYNC[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -max 1.212 [get_ports {mipi_rx_inst1_VALID}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -min 0.466 [get_ports {mipi_rx_inst1_VALID}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -max 1.303 [get_ports {mipi_rx_inst1_CNT[3] mipi_rx_inst1_CNT[2] mipi_rx_inst1_CNT[1] mipi_rx_inst1_CNT[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -min 0.501 [get_ports {mipi_rx_inst1_CNT[3] mipi_rx_inst1_CNT[2] mipi_rx_inst1_CNT[1] mipi_rx_inst1_CNT[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -max 1.339 [get_ports {mipi_rx_inst1_DATA[*]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~64~242}] -min 0.515 [get_ports {mipi_rx_inst1_DATA[*]}]
set_output_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -max 0.733 [get_ports {mipi_rx_inst2_VC_ENA[3] mipi_rx_inst2_VC_ENA[2] mipi_rx_inst2_VC_ENA[1] mipi_rx_inst2_VC_ENA[0]}]
set_output_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -min -0.069 [get_ports {mipi_rx_inst2_VC_ENA[3] mipi_rx_inst2_VC_ENA[2] mipi_rx_inst2_VC_ENA[1] mipi_rx_inst2_VC_ENA[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -max 1.409 [get_ports {mipi_rx_inst2_VSYNC[3] mipi_rx_inst2_VSYNC[2] mipi_rx_inst2_VSYNC[1] mipi_rx_inst2_VSYNC[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -min 0.542 [get_ports {mipi_rx_inst2_VSYNC[3] mipi_rx_inst2_VSYNC[2] mipi_rx_inst2_VSYNC[1] mipi_rx_inst2_VSYNC[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -max 1.401 [get_ports {mipi_rx_inst2_HSYNC[3] mipi_rx_inst2_HSYNC[2] mipi_rx_inst2_HSYNC[1] mipi_rx_inst2_HSYNC[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -min 0.539 [get_ports {mipi_rx_inst2_HSYNC[3] mipi_rx_inst2_HSYNC[2] mipi_rx_inst2_HSYNC[1] mipi_rx_inst2_HSYNC[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -max 1.212 [get_ports {mipi_rx_inst2_VALID}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -min 0.466 [get_ports {mipi_rx_inst2_VALID}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -max 1.303 [get_ports {mipi_rx_inst2_CNT[3] mipi_rx_inst2_CNT[2] mipi_rx_inst2_CNT[1] mipi_rx_inst2_CNT[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -min 0.501 [get_ports {mipi_rx_inst2_CNT[3] mipi_rx_inst2_CNT[2] mipi_rx_inst2_CNT[1] mipi_rx_inst2_CNT[0]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -max 1.339 [get_ports {mipi_rx_inst2_DATA[*]}]
set_input_delay -clock clk -reference_pin [get_ports {clk~CLKOUT~128~242}] -min 0.515 [get_ports {mipi_rx_inst2_DATA[*]}]

# JTAG Constraints
####################
# create_clock -period <USER_PERIOD> -name jtag_inst1_TCK [get_ports {jtag_inst1_TCK}]
set_output_delay -clock jtag_inst1_TCK -max 0.144 [get_ports {jtag_inst1_TDO}]
set_output_delay -clock jtag_inst1_TCK -min -0.053 [get_ports {jtag_inst1_TDO}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.347 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.134 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.347 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.134 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.300 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.116 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.347 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.134 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.417 [get_ports {jtag_inst1_SHIFT}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.161 [get_ports {jtag_inst1_SHIFT}]
# JTAG Constraints (extra... not used by current Efinity debug tools)
# create_clock -period <USER_PERIOD> -name jtag_inst1_DRCK [get_ports {jtag_inst1_DRCK}]
# set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.347 [get_ports {jtag_inst1_RUNTEST}]
# set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.134 [get_ports {jtag_inst1_RUNTEST}]
# Create separate clock groups for JTAG clocks. Remove DRCK clock from the list below if it is not defined.
# set_clock_groups -asynchronous -group {jtag_inst1_TCK jtag_inst1_DRCK}

# Clock Latency Constraints
############################
# set_clock_latency -source -setup <board_max + 1.657> [get_ports {clk}]
# set_clock_latency -source -hold <board_min + 0.637> [get_ports {clk}]
